-   id: markdown-link-check
    name: markdown-link-check
    entry: markdown-link-check --quiet --config=.markdown-link-check.json
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["markdown-link-check@2.0.1"]
